### PR TITLE
corrected a wrong link

### PR DESCRIPTION
**Pull request by irfanurrehman**

### CODE REVIEW

**Comment by glyn** [comment]
Nice catch - thanks. We just need a CLA from you before we can merge this, even though it's a tiny fix.

**Comment by irfanurrehman** [comment]
hello Glyn,

Actually was not very sure about the CLA; for one thing I came to know is that Huawei Tech, the company I work with has signed the CLA. I hadnt had the org name updated in my profile.
I am absolutely new here, and you help/guidance is much appreciated! 
Is there something else suggested to do?

**Comment by glyn** [comment]
@tsaleh: please advise.

**Comment by tsaleh** [comment]
@jbayer Can someone help @irfanurrehman through the CLA process?

**Comment by jbayer** [comment]
@irfanurrehman please get your github name listed publicly in the github org of HuaweiTech which would be here: https://github.com/orgs/HuaweiTech/people

weian deng would be a contact inside huawei to help you with that.

**Comment by irfanurrehman** [comment]
sincere thanks to you all !!

**Comment by irfanurrehman** [comment]
@glyn ,
just to inform that I am now listed as part of huaweitech.
https://github.com/orgs/HuaweiTech/people

**Comment by glyn** [comment]
@irfanurrehman I can't see you listed in https://github.com/orgs/HuaweiTech/people. Did something go wrong?

**Comment by irfanurrehman** [comment]
Apologies, I hadn't changed the listing to public.
Please check now.
thanks again for all your support!

**Comment by glyn** [comment]
Thanks for following up, @irfanurrehman.

**Pull request merged**
